language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- node
- iojs
sudo: false
deploy:
  provider: npm
  email: alex@layton.in
  api_key:
    secure:
  on:
    tags: true
    all_branches: true
    repo: awlayton/require-no-cached
before_install:
 - npm install -g coveralls
script:
- npm run lint
- npm run style
- npm run cover
after_success:
- cat ./coverage/lcov.info | coveralls --verbose
